# Generated by Django 3.1.7 on 2021-04-21 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mpesapayment',
            old_name='organization_balace',
            new_name='organization_balance',
        ),
    ]
